### ISSUE TITLE
NetworkCloudlet isFinished throws NullPointerException

### ISSUE THREAD

**Issue by JabobKrauskopf** [cloudsimplus/cloudsimplus#455]
**Expected behaviour:**
Creating a new `NetworkCloudlet` does not throw an exception

**Actual behaviour:**
Creating a new `NetworkCloudlet`
```java
var cloudlet = new NetworkCloudlet(...);
```
throws a `NullPointerException`.

This is because the `NetworkCloudlet` extends the `CloudletSimple` which in turn extends the `CloudletAbsract`.
The constructor of `CloudletAbstract` calls the `reset` function which at some point calls the `isFinished` function which is overriden by the `NetworkCloudlet`.

The `isFinished` function tries to use the `tasks` variable which has not been assigned yet, because the constructor is still in the `super(id, length, pesNumber)` call.

**Stack Trace:**
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.tasks" is null
	at org.cloudsimplus.cloudlets.network.NetworkCloudlet.isFinished(NetworkCloudlet.java:153)
	at org.cloudsimplus.core.StartableAbstract.setFinishTime(StartableAbstract.java:74)
	at org.cloudsimplus.cloudlets.CloudletAbstract.reset(CloudletAbstract.java:176)
	at org.cloudsimplus.cloudlets.CloudletAbstract.<init>(CloudletAbstract.java:160)
	at org.cloudsimplus.cloudlets.CloudletSimple.<init>(CloudletSimple.java:94)
	at org.cloudsimplus.cloudlets.network.NetworkCloudlet.<init>(NetworkCloudlet.java:75)
	at org.cloudsimplus.cloudlets.network.NetworkCloudlet.<init>(NetworkCloudlet.java:64)
	at me.jakobkraus.ocits.Simulation.main(Simulation.java:49)
```

**Minimum Code for Error:**
```java
import org.cloudsimplus.cloudlets.network.NetworkCloudlet;

public class Simulation {
    public static void main(String[] args) {
        var cloudlet = new NetworkCloudlet(100, 100);
    }
}
```

**Versions used:** `8.5.0` and `8.0.0`

**Comment by JabobKrauskopf** [comment]
This code snippet temporarily fixes the problem for me until the issue is addressed

```java
package me.jakobkraus.ocits.cloudsimplusplus;

import org.cloudsimplus.cloudlets.network.NetworkCloudlet;

import java.util.ArrayList;

public class NetworkCloudletFixed extends NetworkCloudlet {
    public NetworkCloudletFixed(long length, int pesNumber) {
        super(length, pesNumber);
    }

    public NetworkCloudletFixed(int id, long length, int pesNumber) {
        super(id, length, pesNumber);
    }

    @Override
    public boolean isFinished() {
        try {
            var tasksField = NetworkCloudlet.class.getDeclaredField("tasks");
            tasksField.setAccessible(true);
            if (tasksField.get(this) == null) {
                tasksField.set(this, new ArrayList<>());
            }
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
        return super.isFinished();
    }
}
```

**Comment by manoelcampos** [comment]
Hey @JabobKrauskopf 
Thanks for reporting. I've just fixed the issue.
While a new release is not available at maven central, please download the new sources and build the project.
